name: Create Tag

on:
  push:
    branches:
      - master

jobs:
  create-tag:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: git config --global user.email "actions@github.com" && git config --global user.name "GitHub Actions"

    - name: Create tag
      run: |
        version=$(grep -o -P '(?<=version=\")[^"]*' your_version_file)
        git tag -a "v${version}" -m "Version ${version}"
        git push origin "v${version}"
